server:
  port: 9001
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616  #ActiveMQ通讯地址
    #是否启用内存模式（就是不安装MQ，项目启动时同时启动一个MQ实例）
    in-memory: false
    packages:
      trust-all: true      #信任所有的包
    pool:
      enabled: false      #是否替换默认的连接池，使用ActiveMQ的连接池需引入的依赖
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 5000