server:
  port: 10001
spring:
  dubbo:
    application: consumer-one
    registry:
      address: zookeeper://192.168.88.134:2181
    protocol:
      name: dubbo
      port: 20800
    scan: c.s.d.service.impl  #服务暴露与发现消费所在的package
